project:
  type: website
  output-dir: docs

website:
  title: "Notes"
  navbar:
    left:
      - icon: website_favicon.png
        href: https://ehansen.ca
format:
  html:
    theme: cosmo
    css: styles.css



