project:
  type: website
  output-dir: docs

website:
  title: "Notes"
  navbar:
    title: false
    search: false
    left:
      - text: Contents
        href: index.qmd

format:
  html:
    theme: minty
    css: styles.css



