project:
  type: website
  output-dir: docs

website:
  title: "e-vic-github"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: www.ehansen.ca/notes
        text: Back to notes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



