project:
  type: website
  output-dir: docs

website:
  title: "Notes"
  navbar:
    left:
      - text: Back to ehansen.ca
        href: https://www.ehansen.ca
format:
  html:
    theme: cosmo
    css: styles.css



