project:
  type: website
  output-dir: docs

website:
  title: "e-vic-github"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Back to notes
        href: https://www.ehansen.ca/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



